### In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manupulating Tensors
* Tensors & NumPy
* Using @tf.function (a wayt to speed up your regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercise to try for yourself!

### Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.20.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimension of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a Vector
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension ogf vector

vector.ndim

1

In [6]:
# create a matrix

matrix = tf.constant([[10,7],
                      [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix

another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16) # specify the data with dtype

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create a tensor

tensor = tf.constant([[ [1,2,3] ,
                        [1,2,3] ],
                      [ [4,5,6] ,
                        [4,5,6] ],
                      [ [7,8,9] ,
                        [7,8,9] ]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 8, 9]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* matrix: a 2-dim array of numbers
* Tensor: an n-dim array of numbers (where n can be any number, a 0-dim tensor is a scalar, a 1-dim tensor is vector)

### Creating Tensor with tf.Variable


In [12]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# try to change something one of the element in our changable tensor
# changeable_tensor[0] = 7  # item assignment not valid like this

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's try change our unchangable tensor
# unchangeable_tensor[0].assign(7)

### ⚓ Note: Rarely in practice will you need to decide wether to ise tf.constant or tf.Variable to create tensor, as TensorFlow does this for you However, if in doubt use tf.constant and change it later if needed

## Createing Random Tensors

Random tensors are tensors of some arbitary size which contain random numbers

In [16]:
# Create two random (but the same) tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))


In [17]:
# are they equal ?
random_1 == random_2


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [18]:
print(random_1,random_2) # Same

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


### Shuffling The Order Of Elements In A Tensor

Suppose data of ~10000 have 1st- 7000 images have same category (noodels) and other 3000 (soup).

* Thats why we want to shuffle the data



In [19]:
# Shuffle a tensor (Valiable for whem you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,2],
                            [2,5]])
print(not_shuffled.ndim, "\n")
print(not_shuffled.shape, "\n")
not_shuffled



2 

(3, 2) 



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 2,  5]], dtype=int32)>

In [20]:
# shuffle the non_shuffeld data
tf.random.shuffle(not_shuffled, seed=42) # same seed same result


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  2],
       [10,  7]], dtype=int32)>

In [21]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 2,  5]], dtype=int32)>

Global level seed and operational level seed

* tf.random.set_seed(42) # global level random seed

* tf.random.shuffle(not_shuffled, seed=42) # operational level local on only operation



### Turn NumPy array into tensors

The main difference between Numpy arrays and tensorflow tensors is that tensors can be run on GPUs (Much Faster for Numerical computing).


In [22]:
# create a tensor of all ones
tf.ones([7,7])

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
# create a tensor of all zeros
tf.zeros([7,7])

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [24]:
import numpy as np

np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### you can turn Numpy array into tensors

In [26]:
numpy_A = np.arange(1,25,dtype = np.int32) # creating numpy array
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
A = tf.constant(numpy_A) # just passed numpy array
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [28]:
# change the shape

A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [29]:
numpy_A , A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Getting information from tensors

When dealing with tensors you probably went to be aware of the following attributes:
* Shape
* Rank
* Axis or Dimensions
* Size

In [30]:
# Create a rank 4 Tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
# 2 first dimension , 3 second dimension , 4 `x` element , 5 `y` element

'''
2: This is the number of major groups or 'blocks'.
3: Inside each major group, there are 3 rows or 'sub-groups'.
4: Inside each row, there are 4 columns or 'vectors'.
5: Inside each column (vector), there are 5 individual elements.
'''

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
tf.size(rank_4_tensor), rank_4_tensor.ndim , rank_4_tensor.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=120>, 4, TensorShape([2, 3, 4, 5]))

In [32]:
# Get various attributes of our tensor

print("Datatype of every element :", rank_4_tensor.dtype)
print("Number of dimension (rank) :", rank_4_tensor.shape)
print("Shape of Tensor :", rank_4_tensor.ndim)
print("Element along the 0 axis :", rank_4_tensor.shape[0])
print("Element along last axis :", rank_4_tensor.shape[-1])
print("Total number of element in our tensor :", tf.size(rank_4_tensor))
print("Total number of element in our tensor in simple words:", tf.size(rank_4_tensor).numpy())

Datatype of every element : <dtype: 'float32'>
Number of dimension (rank) : (2, 3, 4, 5)
Shape of Tensor : 4
Element along the 0 axis : 2
Element along last axis : 5
Total number of element in our tensor : tf.Tensor(120, shape=(), dtype=int32)
Total number of element in our tensor in simple words: 120


### Indexing and Expanding tensors

### Indexing tensors
* Tensors can be indexed just like Python lists

In [33]:
# Get the first 2 element of each dimension

rank_4_tensor[:2 , :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
# Get the first element for each dimension from each index except for the final one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
# Get the first element for each dimension from each index except for the second last one

rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [36]:
# Create a rank 2 tensor (2 dim)

rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [37]:
# Get the last item of each row

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [38]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor =  rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [39]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor,axis=-1) # "-1 means expand the final axis"

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
# expalnd the 0 axis
tf.expand_dims(rank_2_tensor,axis=0) # "expand the 0 axis"

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors

Basic operations
`+` , `-` , `*`, `/`



In [41]:
# you can add values to a tensor usinbg the addition operator

tensor = tf.constant([[10,7],[3,3]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 13]], dtype=int32)>

In [42]:
# original tensor is unchanged

tensor = tensor + 10
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 13]], dtype=int32)>

In [43]:
# miltiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 130]], dtype=int32)>

In [44]:
# substrachtion if you want

tensor - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-80, -83],
       [-87, -87]], dtype=int32)>

In [45]:
# we can use the tensorflow builtin function too

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 130]], dtype=int32)>

In [46]:
tensor # original dont change

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 13]], dtype=int32)>

### Matrix Multiplication

in machine learning matrix multiplication is one of the most common tensor operation

### There are two rules:

1. inner dimensions must match
2. the resulting matrix has the shape of the outer dimensions

In [47]:
# matrix multiplicaton

print(tensor,"\n")

tf.matmul(tensor,tensor) # matric multiplication

tf.Tensor(
[[20 17]
 [13 13]], shape=(2, 2), dtype=int32) 



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 561],
       [429, 390]], dtype=int32)>

In [48]:
tensor * tensor  # element wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 169]], dtype=int32)>

In [49]:
mat_1 = tf.constant([[1,2,5],
                      [7,2,1],
                      [3,3,3]])

mat_2 = tf.constant([[3,5],
                      [6,7],
                      [1,8]])

tf.matmul(mat_1,mat_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [50]:
# matrix multiplication with python operator "@"

mat_1 @ mat_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [51]:
# create a tensor (3,2)

x = tf.constant([[1,2],
                  [3,4],
                  [5,6]])

y = tf.constant([[7,8],
                  [9,10],
                  [11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [52]:
 # lets change the shape of Y

tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [53]:
# try to multiply x by reshape y

x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [54]:
# try tf.matmul

tf.matmul(x , tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [55]:
# now change the X

tf.matmul(tf.reshape(x,shape=(2,3)),y)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

### The difference between `tf.transpose` and `tf.reshape`

*   **`tf.transpose()`**: Permutes the dimensions of a tensor, effectively swapping or reordering its axes. The elements themselves remain the same, but their arrangement changes based on the new dimension order.

*   **`tf.reshape()`**: Changes the shape of a tensor by reinterpreting its elements into a new configuration of dimensions, without changing the order of the elements. The total number of elements must remain constant.

In [56]:
# Can do the same with transpose

x, tf.transpose(x) , tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [57]:
# try matric multiplication with transopose rather than reshape

tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also reffered to as the dot product.

you can perform matrix matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [58]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [59]:
# perform the dot product on x and y (requiers x or y to be tranposed)


tf.tensordot(tf.transpose(x),y,axes=1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [60]:
# perform mat mul between x and y-transposed

tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [61]:


tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
# check the value of y reshape y and transposed y

print("normal y:",y,"\n")
print("reshape y :",tf.reshape(y,shape=(2,3)),"\n")
print("transposed :",tf.transpose(y),"\n")

normal y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

reshape y : tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

transposed : tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



### change datatype of tensors

In [63]:
# create a new tensor with default datatype int32

b = tf.constant([1.47,7.4])
b.dtype

tf.float32

In [64]:
c = tf.constant([1,7])
c.dtype

tf.int32

### 32 bit to 16 bit conversion is called reduce precision

In [65]:
b = tf.cast(b, dtype = 'float16')
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.47, 7.4 ], dtype=float16)>

In [66]:
c = tf.cast(c, dtype = tf.int16)
c

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>

In [67]:
# change from int32 to float32

e = tf.cast(c, dtype = tf.float16)
e


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>

## Aggregating Tensors

aggregating tensors = condensing them from multiple values down to a smaller amount of values


In [68]:
# get the absolute values

d = tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [69]:
# getting the absolute values

tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation:

* get the minimum
* get the maximum
* get the mean of a tensor
* get the sum of the tensor

In [70]:
# creating a random tensor with values 0 , 100 of size 50

e = tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 52, 56, 49, 93, 45, 21, 19, 92, 34, 52, 15, 93, 76,  9, 96, 82,
       10,  3, 97, 10, 24, 36, 93, 19, 72,  3, 46, 67, 33,  6, 24, 72, 23,
       40, 75, 85, 71, 50, 65, 73, 13, 60, 26, 30, 73, 45, 33, 43,  9])>

In [71]:
tf.size(e), e.shape , e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [72]:
# Find the minimun

tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [73]:
# find the max

tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [74]:
# find the mean

tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [75]:
# find the sum

tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2319>

In [76]:
# find the variance

tf.math.reduce_variance(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=843.3556518554688>

In [77]:
# find the st. dev

tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.040586471557617>

### FIND the positional maximum and minimum

In [78]:
# create a new tensor for finding positional minimum and maximum

tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [79]:
# find the positional maximum
tf.argmax(f) # this return max index

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [80]:
# index on our largest value position

f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [81]:
# another keyword

tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [82]:
# find the positional minimum
tf.argmin(f) # this return min index

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [83]:
# index on our smalleest value position

f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [84]:
# another keyword

tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

### squeezing a tensor (removing all single dimensions)


In [85]:
# create a tensor to started
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [86]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [87]:
g_squeezed = tf.squeeze(g)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [88]:
g_squeezed.shape

TensorShape([50])

### One Hot Encoding Tensors

In [89]:
# create a list of indices

some_list = [0,1,2,3] # could be red , green , blue , purple

# one hot encode our  list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
# specify custom values for one hot encoding

tf.one_hot(some_list , depth=4 , on_value = "Yes", off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'no', b'no', b'no'],
       [b'no', b'Yes', b'no', b'no'],
       [b'no', b'no', b'Yes', b'no'],
       [b'no', b'no', b'no', b'Yes']], dtype=object)>

### Squaring , log, square-root

In [91]:
# create a new tensor
h = tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [92]:
# square it
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [93]:
# square root
tf.sqrt(tf.cast(h,dtype="float32")) # method requires not int type

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [94]:
# find log
tf.math.log(tf.cast(h,dtype="float32"))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

TensorFlow intracts beautifully with NumPy arrays.

In [95]:
# Creates a tensor directly from numpy array
j = tf.constant(np.array([3.,7.,10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [96]:
# convert our tensor back to numpy array
np.array(j) , type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [97]:
# convert tensor j to a NumPy array

np.array(j), type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [98]:
# convert tensor j to a numpy array

j.numpy(), type(j.numpy)

(array([ 3.,  7., 10.]), method)

In [99]:
j = tf.constant([3.])
j.numpy()[0]

np.float32(3.0)

In [100]:
# the default types of each are slightly different
numpy_j = tf.constant(np.array([3.,7.,10]))
tensor_j = tf.constant([3.,7.,10])

# check the datatype of each
numpy_j.dtype , tensor_j.dtype


(tf.float64, tf.float32)

### Finding Access to GPU's:


currently working on cpu

In [101]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

## change runtime to gpu


### Check for GPU Access

If you want to run TensorFlow on a GPU (which is significantly faster for numerical computations), you need to change your Colab runtime type.

To do this, go to `Runtime` > `Change runtime type` in the Colab menu. Then, select `GPU` as the hardware accelerator and click `Save`.

After changing the runtime, you will need to re-run your notebook cells to initialize TensorFlow with GPU support.

In [102]:
# Verify if GPU is now available
print("Is there a GPU available:", tf.config.list_physical_devices('GPU'))


Is there a GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [103]:
# Or to get more details about the GPU:
!nvidia-smi

Tue Jul 14 07:18:43 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P0             26W /   70W |     109MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## If you have access to a CUDA_enabled GPU, TensorFlow will automatically use it whenever possible